### ISSUE TITLE
Stop using default ExecutionContext

### ISSUE THREAD

**Issue by jczuchnowski** [ScalaConsultants/whisky-tango-foxtrot#5]
We're using ActorSystem, so we should use actorSystem.dispatcher instead.

**Comment by margorczynski** [comment]
Fixed in #10 
I've created a _Config_ case class to act basically as a tuple value with all the dependancies/configuration of the application. This should be passed into Reader monads when needed.
I think we should move away from the imperative/OO methods of dependancy injection (cake pattern and implicit value passing) when possible as it is in conflict with basic FP principles (the return value of a function should depend on the passed parameters, not some implictit value imported from God knows where). 
The only implicits left could be those needed by Main which is our gateway into changing the applications state (running DB commands, binding Akka signals, etc.)
@jczuchnowski thoughts about this? I know passing this explicitly could seem more of a hassle but it is much more in line with pure FP principles.
